FROM nwnxee/unified:latest
LABEL maintainer "urothis@gmail.com"
ENV NWN_MODULE=$NWN_MODULE \
    NWN_SERVERNAME=$NWN_SERVERNAME \
    NWN_PORT=$NWN_PORT \
    NWN_PUBLICSERVER=$NWN_PUBLICSERVER \
    NWN_MAXCLIENTS=$NWN_MAXCLIENTS \
    NWN_MINLEVEL=$NWN_MINLEVEL \
    NWN_MAXLEVEL=$NWN_MAXLEVEL \
    NWN_PAUSEANDPLAY=$NWN_PAUSEANDPLAY \
    NWN_PVP=$NWN_PVP \
    NWN_SERVERVAULT=$NWN_SERVERVAULT \
    NWN_ELC=$NWN_ELC \
    NWN_ILR=$NWN_ILR \
    NWN_GAMETYPE=$NWN_GAMETYPE \
    NWN_ONEPARTY=$NWN_ONEPARTY \
    NWN_DIFFICULTY=$NWN_DIFFICULTY \
    NWN_AUTOSAVEINTERVAL=$NWN_AUTOSAVEINTERVAL \
    NWN_RELOADWHENEMPTY=$NWN_RELOADWHENEMPTY \
    NWN_PLAYERPASSWORD=$NWN_PLAYERPASSWORD \
    NWN_DMPASSWORD=$NWN_DMPASSWORD \
    NWN_ADMINPASSWORD=$NWN_ADMINPASSWORD \
    NWNX_CORE_LOG_LEVEL=$NWNX_CORE_LOG_LEVEL \
    NWNX_CORE_SKIP_ALL=$NWNX_CORE_SKIP_ALL \
    NWNX_ADMINISTRATION_SKIP=$NWNX_ADMINISTRATION_SKIP \
    NWNX_CHAT_SKIP=$NWNX_CHAT_SKIP \
    NWNX_CREATURE_SKIP=$NWNX_CREATURE_SKIP \
    NWNX_SQL_SKIP=$NWNX_SQL_SKIP \
    NWNX_TWEAKS_SKIP=$NWNX_TWEAKS_SKIP \
    NWNX_TIME_SKIP=$NWNX_TIME_SKIP \
    NWNX_UTIL_SKIP=$NWNX_UTIL_SKIP \
    NWNX_WEBHOOK_SKIP=$NWNX_WEBHOOK_SKIP \
    NWNX_SQL_TYPE=$NWNX_SQL_TYPE \
    NWNX_SQL_HOST=$NWNX_SQL_HOST \
    NWNX_SQL_DATABASE=$NWNX_SQL_DATABASE \
    NWNX_SQL_USERNAME=$NWNX_SQL_USERNAME \
    NWNX_SQL_PASSWORD=$NWNX_SQL_PASSWORD \
    NWNX_TWEAKS_HIDE_CLASSES_ON_CHAR_LIST=$NWNX_TWEAKS_HIDE_CLASSES_ON_CHAR_LIST \
    NWNX_TWEAKS_DISABLE_PAUSE=$NWNX_TWEAKS_DISABLE_PAUSE \
    NWNX_TWEAKS_HIDE_DMS_ON_CHAR_LIST=$NWNX_TWEAKS_HIDE_DMS_ON_CHAR_LIST \
    NWNX_TWEAKS_DISABLE_MONK_ABILITIES_WHEN_POLYMORPHED=$NWNX_TWEAKS_DISABLE_MONK_ABILITIES_WHEN_POLYMORPHED \
    NWNX_TWEAKS_FIX_GREATER_SANCTUARY_BUG=$NWNX_TWEAKS_FIX_GREATER_SANCTUARY_BUG \
    NWNX_WEBHOOK_PUBLIC_CHANNEL=$NWNX_WEBHOOK_PUBLIC_CHANNEL \
    NWNX_WEBHOOK_PRIVATE_CHANNEL=$NWNX_WEBHOOK_PRIVATE_CHANNEL
COPY $CI_PROJECT_DIR/DungeonEternalX.mod /nwn/home/server/modules/DungeonEternalX.mod
COPY $CI_PROJECT_DIR/disdexBinary usr/local/bin/dexbot
RUN chmod +x usr/local/bin/dexbot
CMD sh -c '/nwn/run-server.sh' \
    && dexbot