FROM nwnxee/unified:latest
LABEL maintainer "urothis@gmail.com"
ENV NWNX_CORE_LOG_LEVEL=6
ENV NWNX_CORE_SHUTDOWN_SCRIPT=_mod_shutdown
ENV NWNX_ADMINISTRATION_SKIP=n
ENV NWNX_CHAT_SKIP=n
ENV NWNX_CREATURE_SKIP=n
ENV NWNX_EVENTS_SKIP=n
ENV NWNX_PLAYER_SKIP=n
ENV NWNX_SQL_SKIP=n
ENV NWNX_TIME_SKIP=n
ENV NWNX_TWEAKS_SKIP=n
ENV NWNX_UTIL_SKIP=n
ENV NWNX_WEBHOOK_SKIP=n

ENV NWNX_SQL_TYPE=MYSQL
ENV NWNX_SQL_DATABASE=dex
ENV NWNX_SQL_HOST=db
ENV NWNX_SQL_USERNAME=dex
ENV NWNX_SQL_PASSWORD=dex

ENV NWNX_REDIS_HOST=redis

ENV NWNX_TWEAKS_DISABLE_MONK_ABILITIES_WHEN_POLYMORPHED=true
ENV NWNX_TWEAKS_DISABLE_PAUSE=true
ENV NWNX_TWEAKS_FIX_GREATER_SANCTUARY_BUG=true
ENV NWNX_TWEAKS_HIDE_CLASSES_ON_CHAR_LIST=true

ENV NWNX_WEBHOOK_PRIVATE_CHANNEL=nope
ENV NWNX_WEBHOOK_PUBLIC_CHANNEL=nope

ENV NWN_AUTOSAVEINTERVAL=0
ENV NWN_DIFFICULTY=3
ENV NWN_DMPASSWORD=jarjarbinks
ENV NWN_ELC=0
ENV NWN_GAMETYPE=0
ENV NWN_ILR=1
ENV NWN_MAXCLIENTS=5
ENV NWN_MAXLEVEL=40
ENV NWN_MINLEVEL=1
ENV NWN_MODULE=DungeonEternalX
ENV NWN_ONEPARTY=0
ENV NWN_PAUSEANDPLAY=0
ENV NWN_PORT=5121
ENV NWN_PUBLICSERVER=0
ENV NWN_PVP=2
ENV NWN_RELOADWHENEMPTY=0
ENV NWN_SERVERVAULT=1
ENV NWN_SERVERNAME=DungeonEternalX
COPY $CI_PROJECT_DIR/DungeonEternalX.mod /nwn/data/data/mod/DungeonEternalX.mod